name: Spring demo GHA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Build with maven
        run : mvn clean package --file pom.xml
      - name: Run Tests
        run: mvn test
        if: ${{contains(github.event.head_commit.message,'test commit')}}